-- Схема для Supabase (выполните в SQL Editor в дашборде Supabase)

-- Таблица магазинов
CREATE TABLE IF NOT EXISTS stores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  logo TEXT
);

-- Таблица товаров
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barcode TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  category TEXT,
  image_url TEXT
);

-- Таблица скидок (deals)
CREATE TABLE IF NOT EXISTS deals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  store_id BIGINT NOT NULL REFERENCES stores(id),
  old_price DECIMAL(10,2) NOT NULL,
  new_price DECIMAL(10,2) NOT NULL,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Индексы
CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode);
CREATE INDEX IF NOT EXISTS idx_deals_created_at ON deals(created_at DESC);

-- Политики RLS (если включены) — пример для публичного чтения и анонимной записи
-- ALTER TABLE products ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE deals ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE stores ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow public read" ON products FOR SELECT USING (true);
-- CREATE POLICY "Allow public read" ON deals FOR SELECT USING (true);
-- CREATE POLICY "Allow public read" ON stores FOR SELECT USING (true);
-- CREATE POLICY "Allow anon insert" ON products FOR INSERT WITH CHECK (true);
-- CREATE POLICY "Allow anon insert" ON deals FOR INSERT WITH CHECK (true);

-- Справочник магазинов
INSERT INTO stores (id, name, logo) VALUES
  (1, 'Пятёрочка', '🛒'),
  (2, 'Магнит', '🏪'),
  (3, 'Перекрёсток', '🛍️'),
  (4, 'Лента', '🏬'),
  (5, 'Ашан', '🏢')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, logo = EXCLUDED.logo;

-- Бакет deal-images: создайте в Supabase Dashboard → Storage → New bucket
-- Имя: deal-images
-- Public bucket: включить (для публичных URL загруженных фото)

-- 1. Создаем таблицу категорий
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Наполняем стартовыми данными
INSERT INTO categories (name) 
VALUES ('Молочные продукты'), ('Хлебобулочные изделия'), ('Мясные изделия'), 
       ('Овощи и фрукты'), ('Крупы'), ('Напитки'), ('Разное')
ON CONFLICT (name) DO NOTHING;

-- 3. Добавляем колонку связи в products
ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES categories(id);

-- 4. Перенос существующих данных (маппинг текста в ID)
-- Сначала создаем категории для всех уникальных названий, которые уже есть в товарах
INSERT INTO categories (name)
SELECT DISTINCT category FROM products 
WHERE category IS NOT NULL
ON CONFLICT (name) DO NOTHING;

-- Проставляем ID соответствующей категории каждому товару
UPDATE products 
SET category_id = categories.id 
FROM categories 
WHERE products.category = categories.name;

-- 5. УДАЛЕНИЕ СТАРОЙ КОЛОНКИ
-- Теперь, когда данные перенесены в category_id, старая текстовая колонка не нужна
ALTER TABLE products DROP COLUMN IF EXISTS category;

-- 6. Безопасность (RLS)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON categories FOR SELECT USING (true);
CREATE POLICY "Allow anon insert" ON categories FOR INSERT WITH CHECK (true);

-- добавляем колонку в таблицу products, чтобы хранить ссылку на сгенерированный штрихкод товара
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS barcode_image_url TEXT;

-- СОЗДАЁМ РЕГИСТРАЦИЮ/АВТОРИЗАЦИЮ ПОЛЬЗОВАТЕЛЕЙ
-- 1. Создаем таблицу профилей
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'moderator', 'admin')),
  full_name TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Включаем RLS (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 3. Настраиваем политики доступа
CREATE POLICY "Профили видимы всем" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Пользователи могут менять свой профиль" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 4. ФУНКЦИЯ-ТРИГГЕР: Автоматическое создание профиля при регистрации
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'user');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Запуск триггера
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- SQL: Создаем универсальный «ключ» админа
-- Функция для проверки, является ли текущий пользователь админом
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN (
    SELECT (role = 'admin')
    FROM public.profiles
    WHERE id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Теперь, когда ты создаешь любую новую таблицу (или для текущих: deals, stores, products), тебе нужно просто включить RLS и бахнуть одну универсальную политику
-- Разрешить админу ВСЁ в таблице (замени 'deals' на имя любой таблицы)
CREATE POLICY "Admins have full access" 
ON public.deals 
FOR ALL 
TO authenticated 
USING (public.is_admin());

-- Разрешить админу ВСЁ в таблице stores
CREATE POLICY "Admins have full access" 
ON public.stores 
FOR ALL 
TO authenticated 
USING (public.is_admin());

-- Разрешить админу ВСЁ в таблице products
CREATE POLICY "Admins have full access" 
ON public.products 
FOR ALL 
TO authenticated 
USING (public.is_admin());

-- Разрешить админу ВСЁ в таблице categories
CREATE POLICY "Admins have full access" 
ON public.categories 
FOR ALL 
TO authenticated 
USING (public.is_admin());

-- 1. Включаем защиту на таблицах (если еще не включена)
-- 1. Гарантируем, что RLS включен (чтобы правила работали одинаково для всех)
ALTER TABLE public.deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 2. Удаляем старые конфликтующие политики (чтобы не было ошибок duplicate)
DROP POLICY IF EXISTS "Все могут смотреть скидки" ON public.deals;
DROP POLICY IF EXISTS "Все могут смотреть магазины" ON public.stores;
DROP POLICY IF EXISTS "Все могут смотреть категории" ON public.categories;
DROP POLICY IF EXISTS "Все могут смотреть товары" ON public.products;

-- 3. Создаем ГЛОБАЛЬНЫЕ разрешения на чтение
-- "TO public" означает "И для гостей, и для залогиненных"
CREATE POLICY "Public Read Access Deals" 
ON public.deals FOR SELECT 
TO public 
USING (true);

CREATE POLICY "Public Read Access Stores" 
ON public.stores FOR SELECT 
TO public 
USING (true);

CREATE POLICY "Public Read Access Categories" 
ON public.categories FOR SELECT 
TO public 
USING (true);

CREATE POLICY "Public Read Access Products" 
ON public.products FOR SELECT 
TO public 
USING (true);

-- Разрешаем пользователям читать СВОЙ собственный профиль
-- Это критично для того, чтобы useAuth мог узнать роль пользователя
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;

CREATE POLICY "Users can view own profile" 
ON public.profiles FOR SELECT 
USING (auth.uid() = id);

-- На всякий случай разрешим вставку самому себе (для регистрации)
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile" 
ON public.profiles FOR INSERT 
WITH CHECK (auth.uid() = id);

-- 1. Удаляем ВООБЩЕ ВСЕ политики с таблицы profiles
DO $$ 
DECLARE pol record;
BEGIN 
    FOR pol IN SELECT policyname FROM pg_policies WHERE tablename = 'profiles' 
    LOOP
        EXECUTE format('DROP POLICY %I ON public.profiles', pol.policyname);
    END LOOP;
END $$;

-- 2. Включаем RLS заново
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 3. Создаем ОДНУ единственную политику: каждый видит только себя
-- Это исключает вызов функций и рекурсию
CREATE POLICY "allow_self_read" 
ON public.profiles FOR SELECT 
TO authenticated 
USING (auth.uid() = id);

-- 4. Даем админам (сервисной роли) доступ ко всему (для внутренних нужд Supabase)
CREATE POLICY "allow_admin_service" 
ON public.profiles FOR ALL 
TO service_role 
USING (true);

-- Создание таблицы типов скидок
CREATE TABLE IF NOT EXISTS deal_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE, -- '2 по цене 1', 'Скидка %', 'Подарок'
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Наполним базовыми типами
INSERT INTO deal_types (name, description) VALUES
('Снижение цены', 'Простое уменьшение стоимости товара'),
('2 по цене 1', 'При покупке двух единиц товара, цена за обе равна цене одной'),
('Подарок при покупке', 'При покупке основного товара выдается дополнительный в подарок');

-- Обновление существующих таблиц
-- Добавляем нужные поля и связи.
-- Обновляем продукты
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS description TEXT;

-- Обновляем магазины
ALTER TABLE stores 
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS parent_id BIGINT REFERENCES stores(id); 
-- parent_id позволит связать "Пятерочку на Ленина" с "Главным офисом Пятерочки" (опционально)

-- Обновляем скидки (deals)
ALTER TABLE deals 
ADD COLUMN IF NOT EXISTS discount_value NUMERIC, -- Для сортировки (например, 25.5 для 25.5%)
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS deal_type_id BIGINT REFERENCES deal_types(id);