-- Схема для Supabase (выполните в SQL Editor в дашборде Supabase)

-- Таблица магазинов
CREATE TABLE IF NOT EXISTS stores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  logo TEXT
);

-- Таблица товаров
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barcode TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  category TEXT,
  image_url TEXT
);

-- Таблица скидок (deals)
CREATE TABLE IF NOT EXISTS deals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  store_id BIGINT NOT NULL REFERENCES stores(id),
  old_price DECIMAL(10,2) NOT NULL,
  new_price DECIMAL(10,2) NOT NULL,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Индексы
CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode);
CREATE INDEX IF NOT EXISTS idx_deals_created_at ON deals(created_at DESC);

-- Политики RLS (если включены) — пример для публичного чтения и анонимной записи
-- ALTER TABLE products ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE deals ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE stores ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow public read" ON products FOR SELECT USING (true);
-- CREATE POLICY "Allow public read" ON deals FOR SELECT USING (true);
-- CREATE POLICY "Allow public read" ON stores FOR SELECT USING (true);
-- CREATE POLICY "Allow anon insert" ON products FOR INSERT WITH CHECK (true);
-- CREATE POLICY "Allow anon insert" ON deals FOR INSERT WITH CHECK (true);

-- Справочник магазинов
INSERT INTO stores (id, name, logo) VALUES
  (1, 'Пятёрочка', '🛒'),
  (2, 'Магнит', '🏪'),
  (3, 'Перекрёсток', '🛍️'),
  (4, 'Лента', '🏬'),
  (5, 'Ашан', '🏢')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, logo = EXCLUDED.logo;

-- Бакет deal-images: создайте в Supabase Dashboard → Storage → New bucket
-- Имя: deal-images
-- Public bucket: включить (для публичных URL загруженных фото)

-- 1. Создаем таблицу категорий
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Наполняем стартовыми данными
INSERT INTO categories (name) 
VALUES ('Молочные продукты'), ('Хлебобулочные изделия'), ('Мясные изделия'), 
       ('Овощи и фрукты'), ('Крупы'), ('Напитки'), ('Разное')
ON CONFLICT (name) DO NOTHING;

-- 3. Добавляем колонку связи в products
ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES categories(id);

-- 4. Перенос существующих данных (маппинг текста в ID)
-- Сначала создаем категории для всех уникальных названий, которые уже есть в товарах
INSERT INTO categories (name)
SELECT DISTINCT category FROM products 
WHERE category IS NOT NULL
ON CONFLICT (name) DO NOTHING;

-- Проставляем ID соответствующей категории каждому товару
UPDATE products 
SET category_id = categories.id 
FROM categories 
WHERE products.category = categories.name;

-- 5. УДАЛЕНИЕ СТАРОЙ КОЛОНКИ
-- Теперь, когда данные перенесены в category_id, старая текстовая колонка не нужна
ALTER TABLE products DROP COLUMN IF EXISTS category;

-- 6. Безопасность (RLS)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON categories FOR SELECT USING (true);
CREATE POLICY "Allow anon insert" ON categories FOR INSERT WITH CHECK (true);

-- добавляем колонку в таблицу products, чтобы хранить ссылку на сгенерированный штрихкод товара
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS barcode_image_url TEXT;